name: Tests

on:
  pull_request: {branches: master}
  push: {branches: master}
  repository_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Read runtime versions
        id: runtime-versions
        run: |
          while read line; do
            lang=$(echo $line | cut -d' ' -f1)
            vsn=$(echo $line | cut -d' ' -f2)
            echo ::set-output name=$lang::$vsn
          done < .tool-versions
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{steps.runtime-versions.outputs.erlang}}
          elixir-version: ${{steps.runtime-versions.outputs.elixir}}
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{runner.os}}-test-${{hashFiles('mix.lock')}}
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: _build/test
          key: ${{runner.os}}-test-${{steps.runtime-versions.outputs.erlang}}-${{steps.runtime-versions.outputs.elixir}}-${{hashFiles('mix.lock')}}
      - name: Fetch dependencies
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run tests
        run: mix test
